export const CHANGE_BASE_VALUE = "CHANGE_BASE_VALUE";
export const CHANGE_CATEGORY = "CHANGE_CATEGORY";

// Currency API Requests
export const CURRENCY_REQUEST_LOADING = "CURRENCY_REQUEST_LOADING";
export const CURRENCY_REQUEST_SUCCESS = "CURRENCY_REQUEST_SUCCESS";
export const CURRENCY_REQUEST_ERROR = "CURRENCY_REQUEST_ERROR";