export const USERNAME_CHANGED = "USERNAME_CHANGED";
export const MESSAGE_SEND_LOADING = "MESSAGE_SEND_LOADING";
export const MESSAGE_SEND_SUCCESS = "MESSAGE_SEND_SUCCESS";
export const MESSAGE_SEND_ERROR = "MESSAGE_SEND_ERROR";
export const MESSAGE_ADD = "MESSAGE_ADD";

export const LOGIN_SUCCESS = "LOGIN_SUCCESS"
export const LOGIN_ERROR = "LOGIN_ERROR"